name: Fetch Calendar Data

on:
  schedule:
    - cron: '0 2 * * *'  # Runs at 2:00 AM UTC every day
  workflow_dispatch:  # Allows manual triggering

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.PAT }}  # This was missing and is crucial
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests python-dotenv

    - name: Run script
      run: python fetch_calendar_data.py
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}

    - name: Commit and push if changed
      if: success()
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git add -A
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update chart data" && git push)
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}