name: Fetch Calendar and Activity Data

on:
  schedule:
    - cron: '0 2 * * *'  # Runs at 2:00 AM UTC every day
  workflow_dispatch:  # Allows manual triggering

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.PAT }}
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    
    - name: Install dependencies
      run: |
        npm install @supabase/supabase-js dotenv

    - name: Run calendar script
      id: fetch_calendar
      run: |
        node utils/fetchAndSaveData.js 2>&1 | tee calendar_output.log
      continue-on-error: true
      env:
        NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
        SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}

    - name: Run activity logs script
      id: fetch_activity
      run: |
        node utils/fetchActivityLogs.js 2>&1 | tee activity_output.log
      continue-on-error: true
      env:
        NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
        SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}

    - name: Check for errors
      id: check_errors
      run: |
        if grep -q "Error" calendar_output.log || grep -q "Error" activity_output.log; then
          echo "Error occurred in script execution:"
          echo "Calendar output:"
          cat calendar_output.log
          echo "Activity output:"
          cat activity_output.log
          echo "Node version:"
          node --version
          echo "Installed packages:"
          npm list
          exit 1
        else
          echo "Data fetch executed successfully"
          echo "Calendar output:"
          cat calendar_output.log
          echo "Activity output:"
          cat activity_output.log
        fi

    - name: List directory contents
      if: failure()
      run: |
        echo "Contents of the current directory:"
        ls -la

    - name: Commit and push if changed
      if: success()
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git add -A
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update chart and activity data" && git push)
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}